// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ruofpsvnqbopbvfokukm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ1b2Zwc3ZucWJvcGJ2Zm9rdWttIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMzcwNjQsImV4cCI6MjA2NDcxMzA2NH0.8_T3NtNuI_Ct2vS6ww_BMzACYzfhKd47IsUA-YITzn0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);